### ISSUE TITLE
Documentation Improvement: Windows Python Module jsonschema Requirement

### ISSUE THREAD

**Issue by jahawkins** [scythe-io/sdk#2]
On first install and validating my first module, I ran into an error with Module Buster where it could not validate my module due to jsonschema Python package missing. This should be added as a prerequisite on Windows in the documentation. 

For those having this issue, I fixed it with:

`python -m pip install jsonschema`

**Comment by farfella** [comment]
Hey @jahawkins.

Not sure jsonschema is necessary in the module's client py or server py. Are you importing jsonschema in your code?

**Comment by jahawkins** [comment]
When I first received this error, I was purely attempting to bust the example module that is created when you use the Create Module feature. Below is the error I get from the Module Validation:

```
Traceback (most recent call last):
  File "wrapper.py", line 17, in <module>
    import modulebuster
  File "C:\Users\[user]\AppData\Local\Temp\testing_ground\modulebuster.py", line 17, in <module>
    import jsonschema
ModuleNotFoundError: No module named 'jsonschema'
```

**Comment by farfella** [comment]
Oh wow. Ick. Thanks! Will do some digging. I think we should either take it out or install it.
